version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
  disable:
    - errcheck
    - gosec
    - dupl
    - gocyclo

run:
  timeout: 5m
  skip-dirs:
    - test
  skip-files:
    - _test\.go

issues:
  exclude:
    - SA9003
    - SA9002
  exclude-dirs:
    - test
  exclude-files:
    - _test\.go
