// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 消息类型
//
// 消息类型范围分配:
//   - 100-149: 元数据操作（Put、Delete、Get 等）
//   - 150-199: Gossip 协议消息
//   - 200-249: Quorum 协议消息
//   - 250-299: 2PC 协议消息
//   - 300-349: 节点管理消息
//   - 350-399: 集群管理消息
type MessageType int32

const (
	// 元数据操作消息 (100-149)
	MessageType_MESSAGE_TYPE_UNSPECIFIED  MessageType = 0
	MessageType_MESSAGE_TYPE_GET          MessageType = 100
	MessageType_MESSAGE_TYPE_PUT          MessageType = 101
	MessageType_MESSAGE_TYPE_DELETE       MessageType = 102
	MessageType_MESSAGE_TYPE_GET_REPLY    MessageType = 103
	MessageType_MESSAGE_TYPE_PUT_REPLY    MessageType = 104
	MessageType_MESSAGE_TYPE_DELETE_REPLY MessageType = 105
	// Gossip 协议消息 (150-199)
	MessageType_MESSAGE_TYPE_GOSSIP_SYNC         MessageType = 150
	MessageType_MESSAGE_TYPE_GOSSIP_SYNC_REPLY   MessageType = 151
	MessageType_MESSAGE_TYPE_GOSSIP_DIGEST       MessageType = 152
	MessageType_MESSAGE_TYPE_GOSSIP_DIGEST_REPLY MessageType = 153
	// Quorum 协议消息 (200-249)
	MessageType_MESSAGE_TYPE_QUORUM_PROPOSE MessageType = 200
	MessageType_MESSAGE_TYPE_QUORUM_VOTE    MessageType = 201
	MessageType_MESSAGE_TYPE_QUORUM_DECIDE  MessageType = 202
	// 2PC 协议消息 (250-299)
	MessageType_MESSAGE_TYPE_2PC_PREPARE        MessageType = 250
	MessageType_MESSAGE_TYPE_2PC_PREPARE_REPLY  MessageType = 251
	MessageType_MESSAGE_TYPE_2PC_COMMIT         MessageType = 252
	MessageType_MESSAGE_TYPE_2PC_ROLLBACK       MessageType = 253
	MessageType_MESSAGE_TYPE_2PC_COMMIT_REPLY   MessageType = 254
	MessageType_MESSAGE_TYPE_2PC_ROLLBACK_REPLY MessageType = 255
	// 节点管理消息 (300-349)
	MessageType_MESSAGE_TYPE_NODE_PING        MessageType = 300
	MessageType_MESSAGE_TYPE_NODE_PONG        MessageType = 301
	MessageType_MESSAGE_TYPE_NODE_JOIN        MessageType = 302
	MessageType_MESSAGE_TYPE_NODE_LEAVE       MessageType = 303
	MessageType_MESSAGE_TYPE_NODE_SYNC        MessageType = 304
	MessageType_MESSAGE_TYPE_CLOCK_SYNC       MessageType = 305
	MessageType_MESSAGE_TYPE_CLOCK_SYNC_REPLY MessageType = 306
	// 集群管理消息 (350-399)
	MessageType_MESSAGE_TYPE_CLUSTER_STATUS       MessageType = 350
	MessageType_MESSAGE_TYPE_CLUSTER_STATUS_REPLY MessageType = 351
	MessageType_MESSAGE_TYPE_LEADER_ELECTION      MessageType = 352
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MESSAGE_TYPE_UNSPECIFIED",
		100: "MESSAGE_TYPE_GET",
		101: "MESSAGE_TYPE_PUT",
		102: "MESSAGE_TYPE_DELETE",
		103: "MESSAGE_TYPE_GET_REPLY",
		104: "MESSAGE_TYPE_PUT_REPLY",
		105: "MESSAGE_TYPE_DELETE_REPLY",
		150: "MESSAGE_TYPE_GOSSIP_SYNC",
		151: "MESSAGE_TYPE_GOSSIP_SYNC_REPLY",
		152: "MESSAGE_TYPE_GOSSIP_DIGEST",
		153: "MESSAGE_TYPE_GOSSIP_DIGEST_REPLY",
		200: "MESSAGE_TYPE_QUORUM_PROPOSE",
		201: "MESSAGE_TYPE_QUORUM_VOTE",
		202: "MESSAGE_TYPE_QUORUM_DECIDE",
		250: "MESSAGE_TYPE_2PC_PREPARE",
		251: "MESSAGE_TYPE_2PC_PREPARE_REPLY",
		252: "MESSAGE_TYPE_2PC_COMMIT",
		253: "MESSAGE_TYPE_2PC_ROLLBACK",
		254: "MESSAGE_TYPE_2PC_COMMIT_REPLY",
		255: "MESSAGE_TYPE_2PC_ROLLBACK_REPLY",
		300: "MESSAGE_TYPE_NODE_PING",
		301: "MESSAGE_TYPE_NODE_PONG",
		302: "MESSAGE_TYPE_NODE_JOIN",
		303: "MESSAGE_TYPE_NODE_LEAVE",
		304: "MESSAGE_TYPE_NODE_SYNC",
		305: "MESSAGE_TYPE_CLOCK_SYNC",
		306: "MESSAGE_TYPE_CLOCK_SYNC_REPLY",
		350: "MESSAGE_TYPE_CLUSTER_STATUS",
		351: "MESSAGE_TYPE_CLUSTER_STATUS_REPLY",
		352: "MESSAGE_TYPE_LEADER_ELECTION",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":          0,
		"MESSAGE_TYPE_GET":                  100,
		"MESSAGE_TYPE_PUT":                  101,
		"MESSAGE_TYPE_DELETE":               102,
		"MESSAGE_TYPE_GET_REPLY":            103,
		"MESSAGE_TYPE_PUT_REPLY":            104,
		"MESSAGE_TYPE_DELETE_REPLY":         105,
		"MESSAGE_TYPE_GOSSIP_SYNC":          150,
		"MESSAGE_TYPE_GOSSIP_SYNC_REPLY":    151,
		"MESSAGE_TYPE_GOSSIP_DIGEST":        152,
		"MESSAGE_TYPE_GOSSIP_DIGEST_REPLY":  153,
		"MESSAGE_TYPE_QUORUM_PROPOSE":       200,
		"MESSAGE_TYPE_QUORUM_VOTE":          201,
		"MESSAGE_TYPE_QUORUM_DECIDE":        202,
		"MESSAGE_TYPE_2PC_PREPARE":          250,
		"MESSAGE_TYPE_2PC_PREPARE_REPLY":    251,
		"MESSAGE_TYPE_2PC_COMMIT":           252,
		"MESSAGE_TYPE_2PC_ROLLBACK":         253,
		"MESSAGE_TYPE_2PC_COMMIT_REPLY":     254,
		"MESSAGE_TYPE_2PC_ROLLBACK_REPLY":   255,
		"MESSAGE_TYPE_NODE_PING":            300,
		"MESSAGE_TYPE_NODE_PONG":            301,
		"MESSAGE_TYPE_NODE_JOIN":            302,
		"MESSAGE_TYPE_NODE_LEAVE":           303,
		"MESSAGE_TYPE_NODE_SYNC":            304,
		"MESSAGE_TYPE_CLOCK_SYNC":           305,
		"MESSAGE_TYPE_CLOCK_SYNC_REPLY":     306,
		"MESSAGE_TYPE_CLUSTER_STATUS":       350,
		"MESSAGE_TYPE_CLUSTER_STATUS_REPLY": 351,
		"MESSAGE_TYPE_LEADER_ELECTION":      352,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type QuorumMessage_VoteType int32

const (
	QuorumMessage_VOTE_TYPE_UNSPECIFIED QuorumMessage_VoteType = 0
	QuorumMessage_VOTE_TYPE_APPROVE     QuorumMessage_VoteType = 1 // 同意
	QuorumMessage_VOTE_TYPE_REJECT      QuorumMessage_VoteType = 2 // 拒绝
)

// Enum value maps for QuorumMessage_VoteType.
var (
	QuorumMessage_VoteType_name = map[int32]string{
		0: "VOTE_TYPE_UNSPECIFIED",
		1: "VOTE_TYPE_APPROVE",
		2: "VOTE_TYPE_REJECT",
	}
	QuorumMessage_VoteType_value = map[string]int32{
		"VOTE_TYPE_UNSPECIFIED": 0,
		"VOTE_TYPE_APPROVE":     1,
		"VOTE_TYPE_REJECT":      2,
	}
)

func (x QuorumMessage_VoteType) Enum() *QuorumMessage_VoteType {
	p := new(QuorumMessage_VoteType)
	*p = x
	return p
}

func (x QuorumMessage_VoteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuorumMessage_VoteType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (QuorumMessage_VoteType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x QuorumMessage_VoteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuorumMessage_VoteType.Descriptor instead.
func (QuorumMessage_VoteType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2, 0}
}

type TwoPCMessage_PhaseType int32

const (
	TwoPCMessage_PHASE_TYPE_UNSPECIFIED TwoPCMessage_PhaseType = 0
	TwoPCMessage_PHASE_TYPE_PREPARE     TwoPCMessage_PhaseType = 1 // 准备阶段
	TwoPCMessage_PHASE_TYPE_COMMIT      TwoPCMessage_PhaseType = 2 // 提交阶段
	TwoPCMessage_PHASE_TYPE_ROLLBACK    TwoPCMessage_PhaseType = 3 // 回滚阶段
)

// Enum value maps for TwoPCMessage_PhaseType.
var (
	TwoPCMessage_PhaseType_name = map[int32]string{
		0: "PHASE_TYPE_UNSPECIFIED",
		1: "PHASE_TYPE_PREPARE",
		2: "PHASE_TYPE_COMMIT",
		3: "PHASE_TYPE_ROLLBACK",
	}
	TwoPCMessage_PhaseType_value = map[string]int32{
		"PHASE_TYPE_UNSPECIFIED": 0,
		"PHASE_TYPE_PREPARE":     1,
		"PHASE_TYPE_COMMIT":      2,
		"PHASE_TYPE_ROLLBACK":    3,
	}
)

func (x TwoPCMessage_PhaseType) Enum() *TwoPCMessage_PhaseType {
	p := new(TwoPCMessage_PhaseType)
	*p = x
	return p
}

func (x TwoPCMessage_PhaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TwoPCMessage_PhaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (TwoPCMessage_PhaseType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x TwoPCMessage_PhaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TwoPCMessage_PhaseType.Descriptor instead.
func (TwoPCMessage_PhaseType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3, 0}
}

type TwoPCMessage_DecisionType int32

const (
	TwoPCMessage_DECISION_TYPE_UNSPECIFIED TwoPCMessage_DecisionType = 0
	TwoPCMessage_DECISION_TYPE_COMMIT      TwoPCMessage_DecisionType = 1 // 提交决策
	TwoPCMessage_DECISION_TYPE_ABORT       TwoPCMessage_DecisionType = 2 // 中止决策
)

// Enum value maps for TwoPCMessage_DecisionType.
var (
	TwoPCMessage_DecisionType_name = map[int32]string{
		0: "DECISION_TYPE_UNSPECIFIED",
		1: "DECISION_TYPE_COMMIT",
		2: "DECISION_TYPE_ABORT",
	}
	TwoPCMessage_DecisionType_value = map[string]int32{
		"DECISION_TYPE_UNSPECIFIED": 0,
		"DECISION_TYPE_COMMIT":      1,
		"DECISION_TYPE_ABORT":       2,
	}
)

func (x TwoPCMessage_DecisionType) Enum() *TwoPCMessage_DecisionType {
	p := new(TwoPCMessage_DecisionType)
	*p = x
	return p
}

func (x TwoPCMessage_DecisionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TwoPCMessage_DecisionType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[3].Descriptor()
}

func (TwoPCMessage_DecisionType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[3]
}

func (x TwoPCMessage_DecisionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TwoPCMessage_DecisionType.Descriptor instead.
func (TwoPCMessage_DecisionType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3, 1}
}

type HeartbeatMessage_StatusType int32

const (
	HeartbeatMessage_STATUS_TYPE_UNSPECIFIED HeartbeatMessage_StatusType = 0
	HeartbeatMessage_STATUS_TYPE_HEALTHY     HeartbeatMessage_StatusType = 1 // 健康
	HeartbeatMessage_STATUS_TYPE_BUSY        HeartbeatMessage_StatusType = 2 // 繁忙
	HeartbeatMessage_STATUS_TYPE_DEGRADED    HeartbeatMessage_StatusType = 3 // 降级
)

// Enum value maps for HeartbeatMessage_StatusType.
var (
	HeartbeatMessage_StatusType_name = map[int32]string{
		0: "STATUS_TYPE_UNSPECIFIED",
		1: "STATUS_TYPE_HEALTHY",
		2: "STATUS_TYPE_BUSY",
		3: "STATUS_TYPE_DEGRADED",
	}
	HeartbeatMessage_StatusType_value = map[string]int32{
		"STATUS_TYPE_UNSPECIFIED": 0,
		"STATUS_TYPE_HEALTHY":     1,
		"STATUS_TYPE_BUSY":        2,
		"STATUS_TYPE_DEGRADED":    3,
	}
)

func (x HeartbeatMessage_StatusType) Enum() *HeartbeatMessage_StatusType {
	p := new(HeartbeatMessage_StatusType)
	*p = x
	return p
}

func (x HeartbeatMessage_StatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartbeatMessage_StatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[4].Descriptor()
}

func (HeartbeatMessage_StatusType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[4]
}

func (x HeartbeatMessage_StatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartbeatMessage_StatusType.Descriptor instead.
func (HeartbeatMessage_StatusType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4, 0}
}

type MetadataOpMessage_OpType int32

const (
	MetadataOpMessage_OP_TYPE_UNSPECIFIED MetadataOpMessage_OpType = 0
	MetadataOpMessage_OP_TYPE_GET         MetadataOpMessage_OpType = 1 // 获取
	MetadataOpMessage_OP_TYPE_PUT         MetadataOpMessage_OpType = 2 // 设置
	MetadataOpMessage_OP_TYPE_DELETE      MetadataOpMessage_OpType = 3 // 删除
	MetadataOpMessage_OP_TYPE_LIST        MetadataOpMessage_OpType = 4 // 列举
)

// Enum value maps for MetadataOpMessage_OpType.
var (
	MetadataOpMessage_OpType_name = map[int32]string{
		0: "OP_TYPE_UNSPECIFIED",
		1: "OP_TYPE_GET",
		2: "OP_TYPE_PUT",
		3: "OP_TYPE_DELETE",
		4: "OP_TYPE_LIST",
	}
	MetadataOpMessage_OpType_value = map[string]int32{
		"OP_TYPE_UNSPECIFIED": 0,
		"OP_TYPE_GET":         1,
		"OP_TYPE_PUT":         2,
		"OP_TYPE_DELETE":      3,
		"OP_TYPE_LIST":        4,
	}
)

func (x MetadataOpMessage_OpType) Enum() *MetadataOpMessage_OpType {
	p := new(MetadataOpMessage_OpType)
	*p = x
	return p
}

func (x MetadataOpMessage_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetadataOpMessage_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[5].Descriptor()
}

func (MetadataOpMessage_OpType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[5]
}

func (x MetadataOpMessage_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetadataOpMessage_OpType.Descriptor instead.
func (MetadataOpMessage_OpType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6, 0}
}

// TransportMessage 传输消息基础结构
//
// 所有消息的通用包装，包含路由信息和时间戳
type TransportMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=nexkv.metadata.MessageType" json:"type,omitempty"` // 消息类型
	Timestamp uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                       // 时间戳（Unix 毫秒）
	FromNode  string                 `protobuf:"bytes,3,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`          // 发送节点 ID
	ToNode    string                 `protobuf:"bytes,4,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`                // 接收节点 ID（可选，广播消息时为空）
	RequestId uint64                 `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`      // 请求 ID（用于匹配请求-响应）
	// Types that are valid to be assigned to Payload:
	//
	//	*TransportMessage_Gossip
	//	*TransportMessage_Quorum
	//	*TransportMessage_Twopc
	//	*TransportMessage_Heartbeat
	//	*TransportMessage_Response
	//	*TransportMessage_Metadata
	Payload       isTransportMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportMessage) Reset() {
	*x = TransportMessage{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportMessage) ProtoMessage() {}

func (x *TransportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportMessage.ProtoReflect.Descriptor instead.
func (*TransportMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *TransportMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *TransportMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransportMessage) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *TransportMessage) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *TransportMessage) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *TransportMessage) GetPayload() isTransportMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TransportMessage) GetGossip() *GossipMessage {
	if x != nil {
		if x, ok := x.Payload.(*TransportMessage_Gossip); ok {
			return x.Gossip
		}
	}
	return nil
}

func (x *TransportMessage) GetQuorum() *QuorumMessage {
	if x != nil {
		if x, ok := x.Payload.(*TransportMessage_Quorum); ok {
			return x.Quorum
		}
	}
	return nil
}

func (x *TransportMessage) GetTwopc() *TwoPCMessage {
	if x != nil {
		if x, ok := x.Payload.(*TransportMessage_Twopc); ok {
			return x.Twopc
		}
	}
	return nil
}

func (x *TransportMessage) GetHeartbeat() *HeartbeatMessage {
	if x != nil {
		if x, ok := x.Payload.(*TransportMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *TransportMessage) GetResponse() *ResponseMessage {
	if x != nil {
		if x, ok := x.Payload.(*TransportMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *TransportMessage) GetMetadata() *MetadataOpMessage {
	if x != nil {
		if x, ok := x.Payload.(*TransportMessage_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

type isTransportMessage_Payload interface {
	isTransportMessage_Payload()
}

type TransportMessage_Gossip struct {
	Gossip *GossipMessage `protobuf:"bytes,10,opt,name=gossip,proto3,oneof"` // Gossip 协议消息
}

type TransportMessage_Quorum struct {
	Quorum *QuorumMessage `protobuf:"bytes,11,opt,name=quorum,proto3,oneof"` // Quorum 协议消息
}

type TransportMessage_Twopc struct {
	Twopc *TwoPCMessage `protobuf:"bytes,12,opt,name=twopc,proto3,oneof"` // 2PC 协议消息
}

type TransportMessage_Heartbeat struct {
	Heartbeat *HeartbeatMessage `protobuf:"bytes,13,opt,name=heartbeat,proto3,oneof"` // 心跳消息
}

type TransportMessage_Response struct {
	Response *ResponseMessage `protobuf:"bytes,14,opt,name=response,proto3,oneof"` // 通用响应消息
}

type TransportMessage_Metadata struct {
	Metadata *MetadataOpMessage `protobuf:"bytes,15,opt,name=metadata,proto3,oneof"` // 元数据操作消息
}

func (*TransportMessage_Gossip) isTransportMessage_Payload() {}

func (*TransportMessage_Quorum) isTransportMessage_Payload() {}

func (*TransportMessage_Twopc) isTransportMessage_Payload() {}

func (*TransportMessage_Heartbeat) isTransportMessage_Payload() {}

func (*TransportMessage_Response) isTransportMessage_Payload() {}

func (*TransportMessage_Metadata) isTransportMessage_Payload() {}

// GossipMessage Gossip 协议消息
//
// 用于节点间元数据的最终一致性同步
type GossipMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                                 // 节点 ID
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                                                            // 元数据版本号
	Metadata      map[string][]byte      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 元数据键值对
	DeletedKeys   []string               `protobuf:"bytes,4,rep,name=deleted_keys,json=deletedKeys,proto3" json:"deleted_keys,omitempty"`                                                  // 已删除的键列表
	Digest        uint32                 `protobuf:"varint,5,opt,name=digest,proto3" json:"digest,omitempty"`                                                                              // 摘要（用于快速比较）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *GossipMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GossipMessage) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GossipMessage) GetMetadata() map[string][]byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GossipMessage) GetDeletedKeys() []string {
	if x != nil {
		return x.DeletedKeys
	}
	return nil
}

func (x *GossipMessage) GetDigest() uint32 {
	if x != nil {
		return x.Digest
	}
	return 0
}

// QuorumMessage Quorum 协议消息
//
// 用于关键元数据的强一致性同步
type QuorumMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposalId    string                 `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`               // 提案 ID（唯一标识）
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                               // 键
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                                           // 值
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                                      // 版本号
	Vote          QuorumMessage_VoteType `protobuf:"varint,5,opt,name=vote,proto3,enum=nexkv.metadata.QuorumMessage_VoteType" json:"vote,omitempty"` // 投票类型（投票消息时使用）
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                         // 拒绝原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuorumMessage) Reset() {
	*x = QuorumMessage{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuorumMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuorumMessage) ProtoMessage() {}

func (x *QuorumMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuorumMessage.ProtoReflect.Descriptor instead.
func (*QuorumMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *QuorumMessage) GetProposalId() string {
	if x != nil {
		return x.ProposalId
	}
	return ""
}

func (x *QuorumMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *QuorumMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *QuorumMessage) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QuorumMessage) GetVote() QuorumMessage_VoteType {
	if x != nil {
		return x.Vote
	}
	return QuorumMessage_VOTE_TYPE_UNSPECIFIED
}

func (x *QuorumMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// TwoPCMessage 两阶段提交消息
//
// 用于跨分片分布式事务
type TwoPCMessage struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	TransactionId string                    `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`                                                // 事务 ID
	Shards        []string                  `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty"`                                                                                   // 涉及的分片列表
	Operations    map[string][]byte         `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 操作列表（key -> operation data）
	Phase         TwoPCMessage_PhaseType    `protobuf:"varint,4,opt,name=phase,proto3,enum=nexkv.metadata.TwoPCMessage_PhaseType" json:"phase,omitempty"`                                         // 当前阶段
	Decision      TwoPCMessage_DecisionType `protobuf:"varint,5,opt,name=decision,proto3,enum=nexkv.metadata.TwoPCMessage_DecisionType" json:"decision,omitempty"`                                // 决策（协调者发送）
	Reason        string                    `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                                                                   // 失败原因（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoPCMessage) Reset() {
	*x = TwoPCMessage{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoPCMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPCMessage) ProtoMessage() {}

func (x *TwoPCMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPCMessage.ProtoReflect.Descriptor instead.
func (*TwoPCMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *TwoPCMessage) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TwoPCMessage) GetShards() []string {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *TwoPCMessage) GetOperations() map[string][]byte {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *TwoPCMessage) GetPhase() TwoPCMessage_PhaseType {
	if x != nil {
		return x.Phase
	}
	return TwoPCMessage_PHASE_TYPE_UNSPECIFIED
}

func (x *TwoPCMessage) GetDecision() TwoPCMessage_DecisionType {
	if x != nil {
		return x.Decision
	}
	return TwoPCMessage_DECISION_TYPE_UNSPECIFIED
}

func (x *TwoPCMessage) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// HeartbeatMessage 心跳消息
//
// 用于节点存活检测和时钟同步
type HeartbeatMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	NodeId        string                      `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                                                                // 节点 ID
	Timestamp     uint64                      `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                       // 时间戳（Unix 毫秒）
	Status        HeartbeatMessage_StatusType `protobuf:"varint,3,opt,name=status,proto3,enum=nexkv.metadata.HeartbeatMessage_StatusType" json:"status,omitempty"`                             // 节点状态
	Metrics       map[string]uint32           `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 节点指标（CPU、内存等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatMessage) GetStatus() HeartbeatMessage_StatusType {
	if x != nil {
		return x.Status
	}
	return HeartbeatMessage_STATUS_TYPE_UNSPECIFIED
}

func (x *HeartbeatMessage) GetMetrics() map[string]uint32 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// ResponseMessage 通用响应消息
//
// 用于所有请求的响应
type ResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                      // 是否成功
	ErrorCode     uint32                 `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误码
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`     // 错误消息
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                             // 响应数据（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResponseMessage) GetErrorCode() uint32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ResponseMessage) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ResponseMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// MetadataOpMessage 元数据操作消息
//
// 用于元数据的增删改查
type MetadataOpMessage struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Op            MetadataOpMessage_OpType `protobuf:"varint,1,opt,name=op,proto3,enum=nexkv.metadata.MetadataOpMessage_OpType" json:"op,omitempty"` // 操作类型
	Key           string                   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                             // 键
	Value         []byte                   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                                         // 值（PUT 时使用）
	Prefix        string                   `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`                                       // 前缀（LIST 时使用）
	Offset        int32                    `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`                                      // 偏移量（LIST 时使用）
	Limit         int32                    `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`                                        // 限制数量（LIST 时使用，0 表示不限制）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataOpMessage) Reset() {
	*x = MetadataOpMessage{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataOpMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataOpMessage) ProtoMessage() {}

func (x *MetadataOpMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataOpMessage.ProtoReflect.Descriptor instead.
func (*MetadataOpMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *MetadataOpMessage) GetOp() MetadataOpMessage_OpType {
	if x != nil {
		return x.Op
	}
	return MetadataOpMessage_OP_TYPE_UNSPECIFIED
}

func (x *MetadataOpMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MetadataOpMessage) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetadataOpMessage) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *MetadataOpMessage) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MetadataOpMessage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x0enexkv.metadata\"\xab\x04\n" +
	"\x10TransportMessage\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.nexkv.metadata.MessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x1b\n" +
	"\tfrom_node\x18\x03 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x04 \x01(\tR\x06toNode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x04R\trequestId\x127\n" +
	"\x06gossip\x18\n" +
	" \x01(\v2\x1d.nexkv.metadata.GossipMessageH\x00R\x06gossip\x127\n" +
	"\x06quorum\x18\v \x01(\v2\x1d.nexkv.metadata.QuorumMessageH\x00R\x06quorum\x124\n" +
	"\x05twopc\x18\f \x01(\v2\x1c.nexkv.metadata.TwoPCMessageH\x00R\x05twopc\x12@\n" +
	"\theartbeat\x18\r \x01(\v2 .nexkv.metadata.HeartbeatMessageH\x00R\theartbeat\x12=\n" +
	"\bresponse\x18\x0e \x01(\v2\x1f.nexkv.metadata.ResponseMessageH\x00R\bresponse\x12?\n" +
	"\bmetadata\x18\x0f \x01(\v2!.nexkv.metadata.MetadataOpMessageH\x00R\bmetadataB\t\n" +
	"\apayload\"\x83\x02\n" +
	"\rGossipMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12G\n" +
	"\bmetadata\x18\x03 \x03(\v2+.nexkv.metadata.GossipMessage.MetadataEntryR\bmetadata\x12!\n" +
	"\fdeleted_keys\x18\x04 \x03(\tR\vdeletedKeys\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\rR\x06digest\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x9a\x02\n" +
	"\rQuorumMessage\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\tR\n" +
	"proposalId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12:\n" +
	"\x04vote\x18\x05 \x01(\x0e2&.nexkv.metadata.QuorumMessage.VoteTypeR\x04vote\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"R\n" +
	"\bVoteType\x12\x19\n" +
	"\x15VOTE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VOTE_TYPE_APPROVE\x10\x01\x12\x14\n" +
	"\x10VOTE_TYPE_REJECT\x10\x02\"\xca\x04\n" +
	"\fTwoPCMessage\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06shards\x18\x02 \x03(\tR\x06shards\x12L\n" +
	"\n" +
	"operations\x18\x03 \x03(\v2,.nexkv.metadata.TwoPCMessage.OperationsEntryR\n" +
	"operations\x12<\n" +
	"\x05phase\x18\x04 \x01(\x0e2&.nexkv.metadata.TwoPCMessage.PhaseTypeR\x05phase\x12E\n" +
	"\bdecision\x18\x05 \x01(\x0e2).nexkv.metadata.TwoPCMessage.DecisionTypeR\bdecision\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x1a=\n" +
	"\x0fOperationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"o\n" +
	"\tPhaseType\x12\x1a\n" +
	"\x16PHASE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PHASE_TYPE_PREPARE\x10\x01\x12\x15\n" +
	"\x11PHASE_TYPE_COMMIT\x10\x02\x12\x17\n" +
	"\x13PHASE_TYPE_ROLLBACK\x10\x03\"`\n" +
	"\fDecisionType\x12\x1d\n" +
	"\x19DECISION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DECISION_TYPE_COMMIT\x10\x01\x12\x17\n" +
	"\x13DECISION_TYPE_ABORT\x10\x02\"\x87\x03\n" +
	"\x10HeartbeatMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12C\n" +
	"\x06status\x18\x03 \x01(\x0e2+.nexkv.metadata.HeartbeatMessage.StatusTypeR\x06status\x12G\n" +
	"\ametrics\x18\x04 \x03(\v2-.nexkv.metadata.HeartbeatMessage.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"r\n" +
	"\n" +
	"StatusType\x12\x1b\n" +
	"\x17STATUS_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STATUS_TYPE_HEALTHY\x10\x01\x12\x14\n" +
	"\x10STATUS_TYPE_BUSY\x10\x02\x12\x18\n" +
	"\x14STATUS_TYPE_DEGRADED\x10\x03\"{\n" +
	"\x0fResponseMessage\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\rR\terrorCode\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xa6\x02\n" +
	"\x11MetadataOpMessage\x128\n" +
	"\x02op\x18\x01 \x01(\x0e2(.nexkv.metadata.MetadataOpMessage.OpTypeR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"i\n" +
	"\x06OpType\x12\x17\n" +
	"\x13OP_TYPE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOP_TYPE_GET\x10\x01\x12\x0f\n" +
	"\vOP_TYPE_PUT\x10\x02\x12\x12\n" +
	"\x0eOP_TYPE_DELETE\x10\x03\x12\x10\n" +
	"\fOP_TYPE_LIST\x10\x04*\xc2\a\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MESSAGE_TYPE_GET\x10d\x12\x14\n" +
	"\x10MESSAGE_TYPE_PUT\x10e\x12\x17\n" +
	"\x13MESSAGE_TYPE_DELETE\x10f\x12\x1a\n" +
	"\x16MESSAGE_TYPE_GET_REPLY\x10g\x12\x1a\n" +
	"\x16MESSAGE_TYPE_PUT_REPLY\x10h\x12\x1d\n" +
	"\x19MESSAGE_TYPE_DELETE_REPLY\x10i\x12\x1d\n" +
	"\x18MESSAGE_TYPE_GOSSIP_SYNC\x10\x96\x01\x12#\n" +
	"\x1eMESSAGE_TYPE_GOSSIP_SYNC_REPLY\x10\x97\x01\x12\x1f\n" +
	"\x1aMESSAGE_TYPE_GOSSIP_DIGEST\x10\x98\x01\x12%\n" +
	" MESSAGE_TYPE_GOSSIP_DIGEST_REPLY\x10\x99\x01\x12 \n" +
	"\x1bMESSAGE_TYPE_QUORUM_PROPOSE\x10\xc8\x01\x12\x1d\n" +
	"\x18MESSAGE_TYPE_QUORUM_VOTE\x10\xc9\x01\x12\x1f\n" +
	"\x1aMESSAGE_TYPE_QUORUM_DECIDE\x10\xca\x01\x12\x1d\n" +
	"\x18MESSAGE_TYPE_2PC_PREPARE\x10\xfa\x01\x12#\n" +
	"\x1eMESSAGE_TYPE_2PC_PREPARE_REPLY\x10\xfb\x01\x12\x1c\n" +
	"\x17MESSAGE_TYPE_2PC_COMMIT\x10\xfc\x01\x12\x1e\n" +
	"\x19MESSAGE_TYPE_2PC_ROLLBACK\x10\xfd\x01\x12\"\n" +
	"\x1dMESSAGE_TYPE_2PC_COMMIT_REPLY\x10\xfe\x01\x12$\n" +
	"\x1fMESSAGE_TYPE_2PC_ROLLBACK_REPLY\x10\xff\x01\x12\x1b\n" +
	"\x16MESSAGE_TYPE_NODE_PING\x10\xac\x02\x12\x1b\n" +
	"\x16MESSAGE_TYPE_NODE_PONG\x10\xad\x02\x12\x1b\n" +
	"\x16MESSAGE_TYPE_NODE_JOIN\x10\xae\x02\x12\x1c\n" +
	"\x17MESSAGE_TYPE_NODE_LEAVE\x10\xaf\x02\x12\x1b\n" +
	"\x16MESSAGE_TYPE_NODE_SYNC\x10\xb0\x02\x12\x1c\n" +
	"\x17MESSAGE_TYPE_CLOCK_SYNC\x10\xb1\x02\x12\"\n" +
	"\x1dMESSAGE_TYPE_CLOCK_SYNC_REPLY\x10\xb2\x02\x12 \n" +
	"\x1bMESSAGE_TYPE_CLUSTER_STATUS\x10\xde\x02\x12&\n" +
	"!MESSAGE_TYPE_CLUSTER_STATUS_REPLY\x10\xdf\x02\x12!\n" +
	"\x1cMESSAGE_TYPE_LEADER_ELECTION\x10\xe0\x02B4Z2github.com/jzhang405/NexKV/internal/metadata/protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_message_proto_goTypes = []any{
	(MessageType)(0),                 // 0: nexkv.metadata.MessageType
	(QuorumMessage_VoteType)(0),      // 1: nexkv.metadata.QuorumMessage.VoteType
	(TwoPCMessage_PhaseType)(0),      // 2: nexkv.metadata.TwoPCMessage.PhaseType
	(TwoPCMessage_DecisionType)(0),   // 3: nexkv.metadata.TwoPCMessage.DecisionType
	(HeartbeatMessage_StatusType)(0), // 4: nexkv.metadata.HeartbeatMessage.StatusType
	(MetadataOpMessage_OpType)(0),    // 5: nexkv.metadata.MetadataOpMessage.OpType
	(*TransportMessage)(nil),         // 6: nexkv.metadata.TransportMessage
	(*GossipMessage)(nil),            // 7: nexkv.metadata.GossipMessage
	(*QuorumMessage)(nil),            // 8: nexkv.metadata.QuorumMessage
	(*TwoPCMessage)(nil),             // 9: nexkv.metadata.TwoPCMessage
	(*HeartbeatMessage)(nil),         // 10: nexkv.metadata.HeartbeatMessage
	(*ResponseMessage)(nil),          // 11: nexkv.metadata.ResponseMessage
	(*MetadataOpMessage)(nil),        // 12: nexkv.metadata.MetadataOpMessage
	nil,                              // 13: nexkv.metadata.GossipMessage.MetadataEntry
	nil,                              // 14: nexkv.metadata.TwoPCMessage.OperationsEntry
	nil,                              // 15: nexkv.metadata.HeartbeatMessage.MetricsEntry
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: nexkv.metadata.TransportMessage.type:type_name -> nexkv.metadata.MessageType
	7,  // 1: nexkv.metadata.TransportMessage.gossip:type_name -> nexkv.metadata.GossipMessage
	8,  // 2: nexkv.metadata.TransportMessage.quorum:type_name -> nexkv.metadata.QuorumMessage
	9,  // 3: nexkv.metadata.TransportMessage.twopc:type_name -> nexkv.metadata.TwoPCMessage
	10, // 4: nexkv.metadata.TransportMessage.heartbeat:type_name -> nexkv.metadata.HeartbeatMessage
	11, // 5: nexkv.metadata.TransportMessage.response:type_name -> nexkv.metadata.ResponseMessage
	12, // 6: nexkv.metadata.TransportMessage.metadata:type_name -> nexkv.metadata.MetadataOpMessage
	13, // 7: nexkv.metadata.GossipMessage.metadata:type_name -> nexkv.metadata.GossipMessage.MetadataEntry
	1,  // 8: nexkv.metadata.QuorumMessage.vote:type_name -> nexkv.metadata.QuorumMessage.VoteType
	14, // 9: nexkv.metadata.TwoPCMessage.operations:type_name -> nexkv.metadata.TwoPCMessage.OperationsEntry
	2,  // 10: nexkv.metadata.TwoPCMessage.phase:type_name -> nexkv.metadata.TwoPCMessage.PhaseType
	3,  // 11: nexkv.metadata.TwoPCMessage.decision:type_name -> nexkv.metadata.TwoPCMessage.DecisionType
	4,  // 12: nexkv.metadata.HeartbeatMessage.status:type_name -> nexkv.metadata.HeartbeatMessage.StatusType
	15, // 13: nexkv.metadata.HeartbeatMessage.metrics:type_name -> nexkv.metadata.HeartbeatMessage.MetricsEntry
	5,  // 14: nexkv.metadata.MetadataOpMessage.op:type_name -> nexkv.metadata.MetadataOpMessage.OpType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	file_message_proto_msgTypes[0].OneofWrappers = []any{
		(*TransportMessage_Gossip)(nil),
		(*TransportMessage_Quorum)(nil),
		(*TransportMessage_Twopc)(nil),
		(*TransportMessage_Heartbeat)(nil),
		(*TransportMessage_Response)(nil),
		(*TransportMessage_Metadata)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
