// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: wal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WALType WAL 操作类型
type WALType int32

const (
	WALType_WAL_TYPE_UNSPECIFIED WALType = 0 // 未指定（占位）
	WALType_WAL_TYPE_PUT         WALType = 1 // 写入操作
	WALType_WAL_TYPE_DELETE      WALType = 2 // 删除操作
	WALType_WAL_TYPE_CHECKPOINT  WALType = 3 // 检查点操作
)

// Enum value maps for WALType.
var (
	WALType_name = map[int32]string{
		0: "WAL_TYPE_UNSPECIFIED",
		1: "WAL_TYPE_PUT",
		2: "WAL_TYPE_DELETE",
		3: "WAL_TYPE_CHECKPOINT",
	}
	WALType_value = map[string]int32{
		"WAL_TYPE_UNSPECIFIED": 0,
		"WAL_TYPE_PUT":         1,
		"WAL_TYPE_DELETE":      2,
		"WAL_TYPE_CHECKPOINT":  3,
	}
)

func (x WALType) Enum() *WALType {
	p := new(WALType)
	*p = x
	return p
}

func (x WALType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WALType) Descriptor() protoreflect.EnumDescriptor {
	return file_wal_proto_enumTypes[0].Descriptor()
}

func (WALType) Type() protoreflect.EnumType {
	return &file_wal_proto_enumTypes[0]
}

func (x WALType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WALType.Descriptor instead.
func (WALType) EnumDescriptor() ([]byte, []int) {
	return file_wal_proto_rawDescGZIP(), []int{0}
}

// HLC 混合逻辑时钟
// HLC = PhysicalTimestamp (8 bytes) + LogicalCounter (2 bytes)
type HLC struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PhysicalTime   uint64                 `protobuf:"varint,1,opt,name=physical_time,json=physicalTime,proto3" json:"physical_time,omitempty"`       // 物理时间戳（Unix 毫秒）
	LogicalCounter uint32                 `protobuf:"varint,2,opt,name=logical_counter,json=logicalCounter,proto3" json:"logical_counter,omitempty"` // 逻辑计数器
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HLC) Reset() {
	*x = HLC{}
	mi := &file_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLC) ProtoMessage() {}

func (x *HLC) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLC.ProtoReflect.Descriptor instead.
func (*HLC) Descriptor() ([]byte, []int) {
	return file_wal_proto_rawDescGZIP(), []int{0}
}

func (x *HLC) GetPhysicalTime() uint64 {
	if x != nil {
		return x.PhysicalTime
	}
	return 0
}

func (x *HLC) GetLogicalCounter() uint32 {
	if x != nil {
		return x.LogicalCounter
	}
	return 0
}

// WALEntry WAL 日志条目
//
// WAL (Write-Ahead Log) 用于崩溃恢复：
//   - 所有写操作先写 WAL，再更新内存表
//   - 崩溃后通过重放 WAL 恢复数据
//   - 定期 checkpoint 清理已应用的日志
type WALEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WALType                `protobuf:"varint,1,opt,name=type,proto3,enum=nexkv.metadata.WALType" json:"type,omitempty"` // 操作类型
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                                // 键
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                            // 值（Type = WAL_TYPE_PUT 时有效）
	OldValue      []byte                 `protobuf:"bytes,4,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`      // 旧值（用于 MVCC 冲突检测，可选）
	Timestamp     *HLC                   `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // 操作时间戳（HLC）
	Checksum      uint32                 `protobuf:"varint,6,opt,name=checksum,proto3" json:"checksum,omitempty"`                     // 校验和（保证数据完整性）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_wal_proto_rawDescGZIP(), []int{1}
}

func (x *WALEntry) GetType() WALType {
	if x != nil {
		return x.Type
	}
	return WALType_WAL_TYPE_UNSPECIFIED
}

func (x *WALEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WALEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WALEntry) GetOldValue() []byte {
	if x != nil {
		return x.OldValue
	}
	return nil
}

func (x *WALEntry) GetTimestamp() *HLC {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WALEntry) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

// MetadataStoreData 元数据存储数据
// 用于快照和完整数据序列化
type MetadataStoreData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string][]byte      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 键值对数据
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                                                    // 版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataStoreData) Reset() {
	*x = MetadataStoreData{}
	mi := &file_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataStoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataStoreData) ProtoMessage() {}

func (x *MetadataStoreData) ProtoReflect() protoreflect.Message {
	mi := &file_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataStoreData.ProtoReflect.Descriptor instead.
func (*MetadataStoreData) Descriptor() ([]byte, []int) {
	return file_wal_proto_rawDescGZIP(), []int{2}
}

func (x *MetadataStoreData) GetData() map[string][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MetadataStoreData) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_wal_proto protoreflect.FileDescriptor

const file_wal_proto_rawDesc = "" +
	"\n" +
	"\twal.proto\x12\x0enexkv.metadata\"S\n" +
	"\x03HLC\x12#\n" +
	"\rphysical_time\x18\x01 \x01(\x04R\fphysicalTime\x12'\n" +
	"\x0flogical_counter\x18\x02 \x01(\rR\x0elogicalCounter\"\xcb\x01\n" +
	"\bWALEntry\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.nexkv.metadata.WALTypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1b\n" +
	"\told_value\x18\x04 \x01(\fR\boldValue\x121\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x13.nexkv.metadata.HLCR\ttimestamp\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\rR\bchecksum\"\xa7\x01\n" +
	"\x11MetadataStoreData\x12?\n" +
	"\x04data\x18\x01 \x03(\v2+.nexkv.metadata.MetadataStoreData.DataEntryR\x04data\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01*c\n" +
	"\aWALType\x12\x18\n" +
	"\x14WAL_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fWAL_TYPE_PUT\x10\x01\x12\x13\n" +
	"\x0fWAL_TYPE_DELETE\x10\x02\x12\x17\n" +
	"\x13WAL_TYPE_CHECKPOINT\x10\x03B4Z2github.com/jzhang405/NexKV/internal/metadata/protob\x06proto3"

var (
	file_wal_proto_rawDescOnce sync.Once
	file_wal_proto_rawDescData []byte
)

func file_wal_proto_rawDescGZIP() []byte {
	file_wal_proto_rawDescOnce.Do(func() {
		file_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wal_proto_rawDesc), len(file_wal_proto_rawDesc)))
	})
	return file_wal_proto_rawDescData
}

var file_wal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wal_proto_goTypes = []any{
	(WALType)(0),              // 0: nexkv.metadata.WALType
	(*HLC)(nil),               // 1: nexkv.metadata.HLC
	(*WALEntry)(nil),          // 2: nexkv.metadata.WALEntry
	(*MetadataStoreData)(nil), // 3: nexkv.metadata.MetadataStoreData
	nil,                       // 4: nexkv.metadata.MetadataStoreData.DataEntry
}
var file_wal_proto_depIdxs = []int32{
	0, // 0: nexkv.metadata.WALEntry.type:type_name -> nexkv.metadata.WALType
	1, // 1: nexkv.metadata.WALEntry.timestamp:type_name -> nexkv.metadata.HLC
	4, // 2: nexkv.metadata.MetadataStoreData.data:type_name -> nexkv.metadata.MetadataStoreData.DataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wal_proto_init() }
func file_wal_proto_init() {
	if File_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wal_proto_rawDesc), len(file_wal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wal_proto_goTypes,
		DependencyIndexes: file_wal_proto_depIdxs,
		EnumInfos:         file_wal_proto_enumTypes,
		MessageInfos:      file_wal_proto_msgTypes,
	}.Build()
	File_wal_proto = out.File
	file_wal_proto_goTypes = nil
	file_wal_proto_depIdxs = nil
}
