// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: transport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecisionState 决策状态
type DecisionState int32

const (
	DecisionState_DECISION_UNDECIDED DecisionState = 0 // 未决策
	DecisionState_DECISION_COMMITTED DecisionState = 1 // 已提交
)

// Enum value maps for DecisionState.
var (
	DecisionState_name = map[int32]string{
		0: "DECISION_UNDECIDED",
		1: "DECISION_COMMITTED",
	}
	DecisionState_value = map[string]int32{
		"DECISION_UNDECIDED": 0,
		"DECISION_COMMITTED": 1,
	}
)

func (x DecisionState) Enum() *DecisionState {
	p := new(DecisionState)
	*p = x
	return p
}

func (x DecisionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionState) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[0].Descriptor()
}

func (DecisionState) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[0]
}

func (x DecisionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionState.Descriptor instead.
func (DecisionState) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

// Phase 2PC 阶段
type Phase int32

const (
	Phase_PHASE_INIT    Phase = 0 // 初始阶段
	Phase_PHASE_PREPARE Phase = 1 // 准备阶段
	Phase_PHASE_DECIDE  Phase = 2 // 决策阶段
	Phase_PHASE_DONE    Phase = 3 // 完成阶段
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_INIT",
		1: "PHASE_PREPARE",
		2: "PHASE_DECIDE",
		3: "PHASE_DONE",
	}
	Phase_value = map[string]int32{
		"PHASE_INIT":    0,
		"PHASE_PREPARE": 1,
		"PHASE_DECIDE":  2,
		"PHASE_DONE":    3,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

// VoteDecision 投票决策
type VoteDecision int32

const (
	VoteDecision_VOTE_UNKNOWN VoteDecision = 0 // 未知
	VoteDecision_VOTE_YES     VoteDecision = 1 // 同意
	VoteDecision_VOTE_NO      VoteDecision = 2 // 拒绝
)

// Enum value maps for VoteDecision.
var (
	VoteDecision_name = map[int32]string{
		0: "VOTE_UNKNOWN",
		1: "VOTE_YES",
		2: "VOTE_NO",
	}
	VoteDecision_value = map[string]int32{
		"VOTE_UNKNOWN": 0,
		"VOTE_YES":     1,
		"VOTE_NO":      2,
	}
)

func (x VoteDecision) Enum() *VoteDecision {
	p := new(VoteDecision)
	*p = x
	return p
}

func (x VoteDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[2].Descriptor()
}

func (VoteDecision) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[2]
}

func (x VoteDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteDecision.Descriptor instead.
func (VoteDecision) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{2}
}

// Knowledge 节点知识
type Knowledge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seen          map[string]bool        `protobuf:"bytes,1,rep,name=seen,proto3" json:"seen,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`       // 已知已投票的节点
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                                                                           // 当前投票版本号
	Decided       map[string]bool        `protobuf:"bytes,3,rep,name=decided,proto3" json:"decided,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 已知已决策的节点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Knowledge) Reset() {
	*x = Knowledge{}
	mi := &file_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Knowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Knowledge) ProtoMessage() {}

func (x *Knowledge) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Knowledge.ProtoReflect.Descriptor instead.
func (*Knowledge) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Knowledge) GetSeen() map[string]bool {
	if x != nil {
		return x.Seen
	}
	return nil
}

func (x *Knowledge) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Knowledge) GetDecided() map[string]bool {
	if x != nil {
		return x.Decided
	}
	return nil
}

// GossipRequest Gossip 交换请求
type GossipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"` // 发送节点 ID
	Knowledge     *Knowledge             `protobuf:"bytes,2,opt,name=knowledge,proto3" json:"knowledge,omitempty"`               // 发送节点的知识
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 时间戳（纳秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipRequest) Reset() {
	*x = GossipRequest{}
	mi := &file_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipRequest) ProtoMessage() {}

func (x *GossipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipRequest.ProtoReflect.Descriptor instead.
func (*GossipRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

func (x *GossipRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *GossipRequest) GetKnowledge() *Knowledge {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

func (x *GossipRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GossipResponse Gossip 交换响应
type GossipResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Accepted        bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`                                     // 是否接受交换
	RemoteKnowledge *Knowledge             `protobuf:"bytes,2,opt,name=remote_knowledge,json=remoteKnowledge,proto3" json:"remote_knowledge,omitempty"` // 远程节点的知识（用于合并）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GossipResponse) Reset() {
	*x = GossipResponse{}
	mi := &file_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipResponse) ProtoMessage() {}

func (x *GossipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipResponse.ProtoReflect.Descriptor instead.
func (*GossipResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{2}
}

func (x *GossipResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *GossipResponse) GetRemoteKnowledge() *Knowledge {
	if x != nil {
		return x.RemoteKnowledge
	}
	return nil
}

// ProposeVoteRequest 发起投票请求
type ProposeVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"` // 发起节点 ID
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                  // 投票版本号
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeVoteRequest) Reset() {
	*x = ProposeVoteRequest{}
	mi := &file_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeVoteRequest) ProtoMessage() {}

func (x *ProposeVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeVoteRequest.ProtoReflect.Descriptor instead.
func (*ProposeVoteRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{3}
}

func (x *ProposeVoteRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *ProposeVoteRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ProposeVoteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ProposeVoteResponse 发起投票响应
type ProposeVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否接受投票
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeVoteResponse) Reset() {
	*x = ProposeVoteResponse{}
	mi := &file_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeVoteResponse) ProtoMessage() {}

func (x *ProposeVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeVoteResponse.ProtoReflect.Descriptor instead.
func (*ProposeVoteResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{4}
}

func (x *ProposeVoteResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// AckVoteRequest 确认投票请求
type AckVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"` // 投票节点 ID
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                  // 投票版本号
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckVoteRequest) Reset() {
	*x = AckVoteRequest{}
	mi := &file_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckVoteRequest) ProtoMessage() {}

func (x *AckVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckVoteRequest.ProtoReflect.Descriptor instead.
func (*AckVoteRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{5}
}

func (x *AckVoteRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *AckVoteRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AckVoteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// AckVoteResponse 确认投票响应
type AckVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否接受确认
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckVoteResponse) Reset() {
	*x = AckVoteResponse{}
	mi := &file_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckVoteResponse) ProtoMessage() {}

func (x *AckVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckVoteResponse.ProtoReflect.Descriptor instead.
func (*AckVoteResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{6}
}

func (x *AckVoteResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// DecisionNotifyRequest 决策通知请求
type DecisionNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`                    // 发送节点 ID
	Decision      DecisionState          `protobuf:"varint,2,opt,name=decision,proto3,enum=nexkv.metadata.DecisionState" json:"decision,omitempty"` // 决策状态
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                                     // 版本号
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                 // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionNotifyRequest) Reset() {
	*x = DecisionNotifyRequest{}
	mi := &file_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionNotifyRequest) ProtoMessage() {}

func (x *DecisionNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionNotifyRequest.ProtoReflect.Descriptor instead.
func (*DecisionNotifyRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{7}
}

func (x *DecisionNotifyRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *DecisionNotifyRequest) GetDecision() DecisionState {
	if x != nil {
		return x.Decision
	}
	return DecisionState_DECISION_UNDECIDED
}

func (x *DecisionNotifyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DecisionNotifyRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DecisionNotifyResponse 决策通知响应
type DecisionNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否接受通知
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionNotifyResponse) Reset() {
	*x = DecisionNotifyResponse{}
	mi := &file_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionNotifyResponse) ProtoMessage() {}

func (x *DecisionNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionNotifyResponse.ProtoReflect.Descriptor instead.
func (*DecisionNotifyResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{8}
}

func (x *DecisionNotifyResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// PrepareRequest Prepare 请求
type PrepareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 事务 ID
	Coordinator   string                 `protobuf:"bytes,2,opt,name=coordinator,proto3" json:"coordinator,omitempty"`                          // 协调者 ID
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareRequest) Reset() {
	*x = PrepareRequest{}
	mi := &file_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareRequest) ProtoMessage() {}

func (x *PrepareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareRequest.ProtoReflect.Descriptor instead.
func (*PrepareRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{9}
}

func (x *PrepareRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PrepareRequest) GetCoordinator() string {
	if x != nil {
		return x.Coordinator
	}
	return ""
}

func (x *PrepareRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// PrepareResponse Prepare 响应
type PrepareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否接受 prepare
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`    // 附加消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareResponse) Reset() {
	*x = PrepareResponse{}
	mi := &file_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareResponse) ProtoMessage() {}

func (x *PrepareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareResponse.ProtoReflect.Descriptor instead.
func (*PrepareResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{10}
}

func (x *PrepareResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PrepareResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// VoteRequest 投票请求
type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 事务 ID
	Participant   string                 `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`                          // 参与者 ID
	Vote          VoteDecision           `protobuf:"varint,3,opt,name=vote,proto3,enum=nexkv.metadata.VoteDecision" json:"vote,omitempty"`      // 投票决策
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{11}
}

func (x *VoteRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *VoteRequest) GetParticipant() string {
	if x != nil {
		return x.Participant
	}
	return ""
}

func (x *VoteRequest) GetVote() VoteDecision {
	if x != nil {
		return x.Vote
	}
	return VoteDecision_VOTE_UNKNOWN
}

func (x *VoteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// VoteResponse 投票响应
type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否接受投票
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`    // 附加消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{12}
}

func (x *VoteResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *VoteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DecisionRequest 决策请求
type DecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 事务 ID
	Coordinator   string                 `protobuf:"bytes,2,opt,name=coordinator,proto3" json:"coordinator,omitempty"`                          // 协调者 ID
	Decision      string                 `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`                                // 决策（commit/rollback）
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{13}
}

func (x *DecisionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DecisionRequest) GetCoordinator() string {
	if x != nil {
		return x.Coordinator
	}
	return ""
}

func (x *DecisionRequest) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *DecisionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// DecisionResponse 决策响应
type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否接受决策
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`    // 附加消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{14}
}

func (x *DecisionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DecisionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AckDecisionRequest 确认决策请求
type AckDecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 事务 ID
	Participant   string                 `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`                          // 参与者 ID
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckDecisionRequest) Reset() {
	*x = AckDecisionRequest{}
	mi := &file_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckDecisionRequest) ProtoMessage() {}

func (x *AckDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckDecisionRequest.ProtoReflect.Descriptor instead.
func (*AckDecisionRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{15}
}

func (x *AckDecisionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AckDecisionRequest) GetParticipant() string {
	if x != nil {
		return x.Participant
	}
	return ""
}

func (x *AckDecisionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// AckDecisionResponse 确认决策响应
type AckDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"` // 是否接受确认
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckDecisionResponse) Reset() {
	*x = AckDecisionResponse{}
	mi := &file_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckDecisionResponse) ProtoMessage() {}

func (x *AckDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckDecisionResponse.ProtoReflect.Descriptor instead.
func (*AckDecisionResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{16}
}

func (x *AckDecisionResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// HealthCheckRequest 健康检查请求
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromNode      string                 `protobuf:"bytes,1,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"` // 请求节点 ID
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // 时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_transport_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{17}
}

func (x *HealthCheckRequest) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *HealthCheckRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HealthCheckResponse 健康检查响应
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`            // 是否健康
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 节点 ID
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`            // 当前版本号
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`             // 附加消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_transport_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{18}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transport_proto protoreflect.FileDescriptor

const file_transport_proto_rawDesc = "" +
	"\n" +
	"\x0ftransport.proto\x12\x0enexkv.metadata\"\x95\x02\n" +
	"\tKnowledge\x127\n" +
	"\x04seen\x18\x01 \x03(\v2#.nexkv.metadata.Knowledge.SeenEntryR\x04seen\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12@\n" +
	"\adecided\x18\x03 \x03(\v2&.nexkv.metadata.Knowledge.DecidedEntryR\adecided\x1a7\n" +
	"\tSeenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a:\n" +
	"\fDecidedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x83\x01\n" +
	"\rGossipRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x127\n" +
	"\tknowledge\x18\x02 \x01(\v2\x19.nexkv.metadata.KnowledgeR\tknowledge\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"r\n" +
	"\x0eGossipResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12D\n" +
	"\x10remote_knowledge\x18\x02 \x01(\v2\x19.nexkv.metadata.KnowledgeR\x0fremoteKnowledge\"i\n" +
	"\x12ProposeVoteRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"1\n" +
	"\x13ProposeVoteResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"e\n" +
	"\x0eAckVoteRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"-\n" +
	"\x0fAckVoteResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xa7\x01\n" +
	"\x15DecisionNotifyRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x129\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x1d.nexkv.metadata.DecisionStateR\bdecision\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"4\n" +
	"\x16DecisionNotifyResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"w\n" +
	"\x0ePrepareRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12 \n" +
	"\vcoordinator\x18\x02 \x01(\tR\vcoordinator\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"G\n" +
	"\x0fPrepareResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\vVoteRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12 \n" +
	"\vparticipant\x18\x02 \x01(\tR\vparticipant\x120\n" +
	"\x04vote\x18\x03 \x01(\x0e2\x1c.nexkv.metadata.VoteDecisionR\x04vote\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"D\n" +
	"\fVoteResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x94\x01\n" +
	"\x0fDecisionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12 \n" +
	"\vcoordinator\x18\x02 \x01(\tR\vcoordinator\x12\x1a\n" +
	"\bdecision\x18\x03 \x01(\tR\bdecision\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"H\n" +
	"\x10DecisionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\x12AckDecisionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12 \n" +
	"\vparticipant\x18\x02 \x01(\tR\vparticipant\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"1\n" +
	"\x13AckDecisionResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"O\n" +
	"\x12HealthCheckRequest\x12\x1b\n" +
	"\tfrom_node\x18\x01 \x01(\tR\bfromNode\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"|\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*?\n" +
	"\rDecisionState\x12\x16\n" +
	"\x12DECISION_UNDECIDED\x10\x00\x12\x16\n" +
	"\x12DECISION_COMMITTED\x10\x01*L\n" +
	"\x05Phase\x12\x0e\n" +
	"\n" +
	"PHASE_INIT\x10\x00\x12\x11\n" +
	"\rPHASE_PREPARE\x10\x01\x12\x10\n" +
	"\fPHASE_DECIDE\x10\x02\x12\x0e\n" +
	"\n" +
	"PHASE_DONE\x10\x03*;\n" +
	"\fVoteDecision\x12\x10\n" +
	"\fVOTE_UNKNOWN\x10\x00\x12\f\n" +
	"\bVOTE_YES\x10\x01\x12\v\n" +
	"\aVOTE_NO\x10\x022\x83\x06\n" +
	"\x11MetadataTransport\x12O\n" +
	"\x0eGossipExchange\x12\x1d.nexkv.metadata.GossipRequest\x1a\x1e.nexkv.metadata.GossipResponse\x12V\n" +
	"\vProposeVote\x12\".nexkv.metadata.ProposeVoteRequest\x1a#.nexkv.metadata.ProposeVoteResponse\x12J\n" +
	"\aAckVote\x12\x1e.nexkv.metadata.AckVoteRequest\x1a\x1f.nexkv.metadata.AckVoteResponse\x12_\n" +
	"\x0eDecisionNotify\x12%.nexkv.metadata.DecisionNotifyRequest\x1a&.nexkv.metadata.DecisionNotifyResponse\x12N\n" +
	"\vSendPrepare\x12\x1e.nexkv.metadata.PrepareRequest\x1a\x1f.nexkv.metadata.PrepareResponse\x12E\n" +
	"\bSendVote\x12\x1b.nexkv.metadata.VoteRequest\x1a\x1c.nexkv.metadata.VoteResponse\x12Q\n" +
	"\fSendDecision\x12\x1f.nexkv.metadata.DecisionRequest\x1a .nexkv.metadata.DecisionResponse\x12V\n" +
	"\vAckDecision\x12\".nexkv.metadata.AckDecisionRequest\x1a#.nexkv.metadata.AckDecisionResponse\x12V\n" +
	"\vHealthCheck\x12\".nexkv.metadata.HealthCheckRequest\x1a#.nexkv.metadata.HealthCheckResponseB\"Z github.com/jzhang405/NexKV/protob\x06proto3"

var (
	file_transport_proto_rawDescOnce sync.Once
	file_transport_proto_rawDescData []byte
)

func file_transport_proto_rawDescGZIP() []byte {
	file_transport_proto_rawDescOnce.Do(func() {
		file_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)))
	})
	return file_transport_proto_rawDescData
}

var file_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_transport_proto_goTypes = []any{
	(DecisionState)(0),             // 0: nexkv.metadata.DecisionState
	(Phase)(0),                     // 1: nexkv.metadata.Phase
	(VoteDecision)(0),              // 2: nexkv.metadata.VoteDecision
	(*Knowledge)(nil),              // 3: nexkv.metadata.Knowledge
	(*GossipRequest)(nil),          // 4: nexkv.metadata.GossipRequest
	(*GossipResponse)(nil),         // 5: nexkv.metadata.GossipResponse
	(*ProposeVoteRequest)(nil),     // 6: nexkv.metadata.ProposeVoteRequest
	(*ProposeVoteResponse)(nil),    // 7: nexkv.metadata.ProposeVoteResponse
	(*AckVoteRequest)(nil),         // 8: nexkv.metadata.AckVoteRequest
	(*AckVoteResponse)(nil),        // 9: nexkv.metadata.AckVoteResponse
	(*DecisionNotifyRequest)(nil),  // 10: nexkv.metadata.DecisionNotifyRequest
	(*DecisionNotifyResponse)(nil), // 11: nexkv.metadata.DecisionNotifyResponse
	(*PrepareRequest)(nil),         // 12: nexkv.metadata.PrepareRequest
	(*PrepareResponse)(nil),        // 13: nexkv.metadata.PrepareResponse
	(*VoteRequest)(nil),            // 14: nexkv.metadata.VoteRequest
	(*VoteResponse)(nil),           // 15: nexkv.metadata.VoteResponse
	(*DecisionRequest)(nil),        // 16: nexkv.metadata.DecisionRequest
	(*DecisionResponse)(nil),       // 17: nexkv.metadata.DecisionResponse
	(*AckDecisionRequest)(nil),     // 18: nexkv.metadata.AckDecisionRequest
	(*AckDecisionResponse)(nil),    // 19: nexkv.metadata.AckDecisionResponse
	(*HealthCheckRequest)(nil),     // 20: nexkv.metadata.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 21: nexkv.metadata.HealthCheckResponse
	nil,                            // 22: nexkv.metadata.Knowledge.SeenEntry
	nil,                            // 23: nexkv.metadata.Knowledge.DecidedEntry
}
var file_transport_proto_depIdxs = []int32{
	22, // 0: nexkv.metadata.Knowledge.seen:type_name -> nexkv.metadata.Knowledge.SeenEntry
	23, // 1: nexkv.metadata.Knowledge.decided:type_name -> nexkv.metadata.Knowledge.DecidedEntry
	3,  // 2: nexkv.metadata.GossipRequest.knowledge:type_name -> nexkv.metadata.Knowledge
	3,  // 3: nexkv.metadata.GossipResponse.remote_knowledge:type_name -> nexkv.metadata.Knowledge
	0,  // 4: nexkv.metadata.DecisionNotifyRequest.decision:type_name -> nexkv.metadata.DecisionState
	2,  // 5: nexkv.metadata.VoteRequest.vote:type_name -> nexkv.metadata.VoteDecision
	4,  // 6: nexkv.metadata.MetadataTransport.GossipExchange:input_type -> nexkv.metadata.GossipRequest
	6,  // 7: nexkv.metadata.MetadataTransport.ProposeVote:input_type -> nexkv.metadata.ProposeVoteRequest
	8,  // 8: nexkv.metadata.MetadataTransport.AckVote:input_type -> nexkv.metadata.AckVoteRequest
	10, // 9: nexkv.metadata.MetadataTransport.DecisionNotify:input_type -> nexkv.metadata.DecisionNotifyRequest
	12, // 10: nexkv.metadata.MetadataTransport.SendPrepare:input_type -> nexkv.metadata.PrepareRequest
	14, // 11: nexkv.metadata.MetadataTransport.SendVote:input_type -> nexkv.metadata.VoteRequest
	16, // 12: nexkv.metadata.MetadataTransport.SendDecision:input_type -> nexkv.metadata.DecisionRequest
	18, // 13: nexkv.metadata.MetadataTransport.AckDecision:input_type -> nexkv.metadata.AckDecisionRequest
	20, // 14: nexkv.metadata.MetadataTransport.HealthCheck:input_type -> nexkv.metadata.HealthCheckRequest
	5,  // 15: nexkv.metadata.MetadataTransport.GossipExchange:output_type -> nexkv.metadata.GossipResponse
	7,  // 16: nexkv.metadata.MetadataTransport.ProposeVote:output_type -> nexkv.metadata.ProposeVoteResponse
	9,  // 17: nexkv.metadata.MetadataTransport.AckVote:output_type -> nexkv.metadata.AckVoteResponse
	11, // 18: nexkv.metadata.MetadataTransport.DecisionNotify:output_type -> nexkv.metadata.DecisionNotifyResponse
	13, // 19: nexkv.metadata.MetadataTransport.SendPrepare:output_type -> nexkv.metadata.PrepareResponse
	15, // 20: nexkv.metadata.MetadataTransport.SendVote:output_type -> nexkv.metadata.VoteResponse
	17, // 21: nexkv.metadata.MetadataTransport.SendDecision:output_type -> nexkv.metadata.DecisionResponse
	19, // 22: nexkv.metadata.MetadataTransport.AckDecision:output_type -> nexkv.metadata.AckDecisionResponse
	21, // 23: nexkv.metadata.MetadataTransport.HealthCheck:output_type -> nexkv.metadata.HealthCheckResponse
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_transport_proto_init() }
func file_transport_proto_init() {
	if File_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transport_proto_goTypes,
		DependencyIndexes: file_transport_proto_depIdxs,
		EnumInfos:         file_transport_proto_enumTypes,
		MessageInfos:      file_transport_proto_msgTypes,
	}.Build()
	File_transport_proto = out.File
	file_transport_proto_goTypes = nil
	file_transport_proto_depIdxs = nil
}
