// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: transport.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataTransport_GossipExchange_FullMethodName = "/nexkv.metadata.MetadataTransport/GossipExchange"
	MetadataTransport_ProposeVote_FullMethodName    = "/nexkv.metadata.MetadataTransport/ProposeVote"
	MetadataTransport_AckVote_FullMethodName        = "/nexkv.metadata.MetadataTransport/AckVote"
	MetadataTransport_DecisionNotify_FullMethodName = "/nexkv.metadata.MetadataTransport/DecisionNotify"
	MetadataTransport_SendPrepare_FullMethodName    = "/nexkv.metadata.MetadataTransport/SendPrepare"
	MetadataTransport_SendVote_FullMethodName       = "/nexkv.metadata.MetadataTransport/SendVote"
	MetadataTransport_SendDecision_FullMethodName   = "/nexkv.metadata.MetadataTransport/SendDecision"
	MetadataTransport_AckDecision_FullMethodName    = "/nexkv.metadata.MetadataTransport/AckDecision"
	MetadataTransport_HealthCheck_FullMethodName    = "/nexkv.metadata.MetadataTransport/HealthCheck"
)

// MetadataTransportClient is the client API for MetadataTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// # MetadataTransport - 元数据层传输服务
//
// 这个服务定义了 NexKV 元数据层节点间的通信协议。
// 支持 Gossip 协议、投票机制、2PC 提交协议等。
type MetadataTransportClient interface {
	// GossipExchange 节点间知识交换
	//
	// 用于传播节点的投票状态和决策状态。
	// 这是最终一致性协议的核心消息类型。
	GossipExchange(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error)
	// ProposeVote 发起投票提议
	//
	// 节点发起对一个版本的投票。
	ProposeVote(ctx context.Context, in *ProposeVoteRequest, opts ...grpc.CallOption) (*ProposeVoteResponse, error)
	// AckVote 确认投票
	//
	// 节点确认自己已经投票。
	AckVote(ctx context.Context, in *AckVoteRequest, opts ...grpc.CallOption) (*AckVoteResponse, error)
	// DecisionNotify 决策通知
	//
	// 节点通知其他节点自己的决策状态。
	DecisionNotify(ctx context.Context, in *DecisionNotifyRequest, opts ...grpc.CallOption) (*DecisionNotifyResponse, error)
	// SendPrepare 发送 Prepare 阶段请求
	//
	// 协调者向参与者发送 prepare 请求。
	SendPrepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error)
	// SendVote 发送投票决策
	//
	// 参与者向协调者发送投票结果（yes/no）。
	SendVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error)
	// SendDecision 发送最终决策
	//
	// 协调者向参与者发送最终决策（commit/rollback）。
	SendDecision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
	// AckDecision 确认决策
	//
	// 参与者确认收到最终决策。
	AckDecision(ctx context.Context, in *AckDecisionRequest, opts ...grpc.CallOption) (*AckDecisionResponse, error)
	// HealthCheck 健康检查
	//
	// 用于检测节点是否可达和正常工作。
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type metadataTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataTransportClient(cc grpc.ClientConnInterface) MetadataTransportClient {
	return &metadataTransportClient{cc}
}

func (c *metadataTransportClient) GossipExchange(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*GossipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_GossipExchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataTransportClient) ProposeVote(ctx context.Context, in *ProposeVoteRequest, opts ...grpc.CallOption) (*ProposeVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposeVoteResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_ProposeVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataTransportClient) AckVote(ctx context.Context, in *AckVoteRequest, opts ...grpc.CallOption) (*AckVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckVoteResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_AckVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataTransportClient) DecisionNotify(ctx context.Context, in *DecisionNotifyRequest, opts ...grpc.CallOption) (*DecisionNotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionNotifyResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_DecisionNotify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataTransportClient) SendPrepare(ctx context.Context, in *PrepareRequest, opts ...grpc.CallOption) (*PrepareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_SendPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataTransportClient) SendVote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*VoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VoteResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_SendVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataTransportClient) SendDecision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_SendDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataTransportClient) AckDecision(ctx context.Context, in *AckDecisionRequest, opts ...grpc.CallOption) (*AckDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckDecisionResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_AckDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataTransportClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MetadataTransport_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataTransportServer is the server API for MetadataTransport service.
// All implementations must embed UnimplementedMetadataTransportServer
// for forward compatibility.
//
// # MetadataTransport - 元数据层传输服务
//
// 这个服务定义了 NexKV 元数据层节点间的通信协议。
// 支持 Gossip 协议、投票机制、2PC 提交协议等。
type MetadataTransportServer interface {
	// GossipExchange 节点间知识交换
	//
	// 用于传播节点的投票状态和决策状态。
	// 这是最终一致性协议的核心消息类型。
	GossipExchange(context.Context, *GossipRequest) (*GossipResponse, error)
	// ProposeVote 发起投票提议
	//
	// 节点发起对一个版本的投票。
	ProposeVote(context.Context, *ProposeVoteRequest) (*ProposeVoteResponse, error)
	// AckVote 确认投票
	//
	// 节点确认自己已经投票。
	AckVote(context.Context, *AckVoteRequest) (*AckVoteResponse, error)
	// DecisionNotify 决策通知
	//
	// 节点通知其他节点自己的决策状态。
	DecisionNotify(context.Context, *DecisionNotifyRequest) (*DecisionNotifyResponse, error)
	// SendPrepare 发送 Prepare 阶段请求
	//
	// 协调者向参与者发送 prepare 请求。
	SendPrepare(context.Context, *PrepareRequest) (*PrepareResponse, error)
	// SendVote 发送投票决策
	//
	// 参与者向协调者发送投票结果（yes/no）。
	SendVote(context.Context, *VoteRequest) (*VoteResponse, error)
	// SendDecision 发送最终决策
	//
	// 协调者向参与者发送最终决策（commit/rollback）。
	SendDecision(context.Context, *DecisionRequest) (*DecisionResponse, error)
	// AckDecision 确认决策
	//
	// 参与者确认收到最终决策。
	AckDecision(context.Context, *AckDecisionRequest) (*AckDecisionResponse, error)
	// HealthCheck 健康检查
	//
	// 用于检测节点是否可达和正常工作。
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMetadataTransportServer()
}

// UnimplementedMetadataTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataTransportServer struct{}

func (UnimplementedMetadataTransportServer) GossipExchange(context.Context, *GossipRequest) (*GossipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GossipExchange not implemented")
}
func (UnimplementedMetadataTransportServer) ProposeVote(context.Context, *ProposeVoteRequest) (*ProposeVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeVote not implemented")
}
func (UnimplementedMetadataTransportServer) AckVote(context.Context, *AckVoteRequest) (*AckVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckVote not implemented")
}
func (UnimplementedMetadataTransportServer) DecisionNotify(context.Context, *DecisionNotifyRequest) (*DecisionNotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecisionNotify not implemented")
}
func (UnimplementedMetadataTransportServer) SendPrepare(context.Context, *PrepareRequest) (*PrepareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPrepare not implemented")
}
func (UnimplementedMetadataTransportServer) SendVote(context.Context, *VoteRequest) (*VoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVote not implemented")
}
func (UnimplementedMetadataTransportServer) SendDecision(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendDecision not implemented")
}
func (UnimplementedMetadataTransportServer) AckDecision(context.Context, *AckDecisionRequest) (*AckDecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckDecision not implemented")
}
func (UnimplementedMetadataTransportServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMetadataTransportServer) mustEmbedUnimplementedMetadataTransportServer() {}
func (UnimplementedMetadataTransportServer) testEmbeddedByValue()                           {}

// UnsafeMetadataTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataTransportServer will
// result in compilation errors.
type UnsafeMetadataTransportServer interface {
	mustEmbedUnimplementedMetadataTransportServer()
}

func RegisterMetadataTransportServer(s grpc.ServiceRegistrar, srv MetadataTransportServer) {
	// If the following call panics, it indicates UnimplementedMetadataTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataTransport_ServiceDesc, srv)
}

func _MetadataTransport_GossipExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).GossipExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_GossipExchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).GossipExchange(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataTransport_ProposeVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProposeVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).ProposeVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_ProposeVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).ProposeVote(ctx, req.(*ProposeVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataTransport_AckVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).AckVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_AckVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).AckVote(ctx, req.(*AckVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataTransport_DecisionNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).DecisionNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_DecisionNotify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).DecisionNotify(ctx, req.(*DecisionNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataTransport_SendPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).SendPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_SendPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).SendPrepare(ctx, req.(*PrepareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataTransport_SendVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).SendVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_SendVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).SendVote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataTransport_SendDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).SendDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_SendDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).SendDecision(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataTransport_AckDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).AckDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_AckDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).AckDecision(ctx, req.(*AckDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataTransport_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataTransportServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataTransport_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataTransportServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataTransport_ServiceDesc is the grpc.ServiceDesc for MetadataTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexkv.metadata.MetadataTransport",
	HandlerType: (*MetadataTransportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GossipExchange",
			Handler:    _MetadataTransport_GossipExchange_Handler,
		},
		{
			MethodName: "ProposeVote",
			Handler:    _MetadataTransport_ProposeVote_Handler,
		},
		{
			MethodName: "AckVote",
			Handler:    _MetadataTransport_AckVote_Handler,
		},
		{
			MethodName: "DecisionNotify",
			Handler:    _MetadataTransport_DecisionNotify_Handler,
		},
		{
			MethodName: "SendPrepare",
			Handler:    _MetadataTransport_SendPrepare_Handler,
		},
		{
			MethodName: "SendVote",
			Handler:    _MetadataTransport_SendVote_Handler,
		},
		{
			MethodName: "SendDecision",
			Handler:    _MetadataTransport_SendDecision_Handler,
		},
		{
			MethodName: "AckDecision",
			Handler:    _MetadataTransport_AckDecision_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MetadataTransport_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transport.proto",
}
